// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVy25HKDUJwuiXCrjk5Mi23wRRsMrXcI',
    appId: '1:176779707540:web:a6976c8691fab0b5232081',
    messagingSenderId: '176779707540',
    projectId: 'masruf-9a12b',
    authDomain: 'masruf-9a12b.firebaseapp.com',
    storageBucket: 'masruf-9a12b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHAfJA6yoyk_-Gb0lUYtSW3B6SoPvEx0o',
    appId: '1:176779707540:android:da459b795d1f2991232081',
    messagingSenderId: '176779707540',
    projectId: 'masruf-9a12b',
    storageBucket: 'masruf-9a12b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSd7Xu0xZOcj8chLECK0P9mqdYZRh_nb8',
    appId: '1:176779707540:ios:b3003e0c2275ba3e232081',
    messagingSenderId: '176779707540',
    projectId: 'masruf-9a12b',
    storageBucket: 'masruf-9a12b.firebasestorage.app',
    iosClientId: '176779707540-94mlj8ope5tad5ransco6ucc2j02e5o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSd7Xu0xZOcj8chLECK0P9mqdYZRh_nb8',
    appId: '1:176779707540:ios:b3003e0c2275ba3e232081',
    messagingSenderId: '176779707540',
    projectId: 'masruf-9a12b',
    storageBucket: 'masruf-9a12b.firebasestorage.app',
    iosClientId: '176779707540-94mlj8ope5tad5ransco6ucc2j02e5o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbVy25HKDUJwuiXCrjk5Mi23wRRsMrXcI',
    appId: '1:176779707540:web:1a42f29d638cf23c232081',
    messagingSenderId: '176779707540',
    projectId: 'masruf-9a12b',
    authDomain: 'masruf-9a12b.firebaseapp.com',
    storageBucket: 'masruf-9a12b.firebasestorage.app',
  );

}